name: ci-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: simple_bank

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install go-migrate CLI
        # run a multi-line command
        # download the binary migrate from the url
        # mv the binary to /usr/bin
        # wich migrate to see if the binay is there (works by locating the executable file matching the given command)
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          wich migrate

      - name: Run db migration
        run: make migrateup

      - name: Test
        run: make test
